POST http://localhost:3333/usuarios
Content-Type: application/json

{
    "nome": "Produto novo 02",
    "email": "Modelo Teste",
    "senha": "2025-01-01"
}

###

GET http://localhost:3333/usuarios

###

PUT http://localhost:3333/usuarios/1
Content-Type: application/json

{
    "nome": "matador de onça",
    "email": "Modelo Teste",
    "senha": "2025-01-02"
}

###

DELETE http://localhost:3333/usuarios/1