POST http://3.144.136.94:3000/usuarios
Content-Type: application/json

{
    "nome": "Produto novo 02",
    "email": "Modelo Teste",
    "senha": "2025-01-01"
}

###

GET http://3.144.136.94:3000/usuarios

###

PUT http://3.144.136.94:3000/usuarios/1
Content-Type: application/json

{
    "nome": "matador de onça",
    "email": "Modelo Teste",
    "senha": "2025-01-02"
}

###

DELETE http://3.144.136.94:3000/usuarios/1